_wandb:
    value:
        cli_version: 0.19.8
        code_path: code/pretrain/whispa_train.py
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.19.8
            "6": 4.50.3
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
acoustic_teacher_id:
    value: facebook/hubert-large-ls960-ft
alpha:
    value: 0.5
batch_size:
    value: 2
beta:
    value: 0.5
device:
    value: cuda
hidden_size:
    value: 1024
learning_rate:
    value: 5e-05
linguistic_teacher_id:
    value: jinaai/jina-embeddings-v3
loss:
    value: DWD
n_new_dims:
    value: 0
num_epochs:
    value: 1
num_workers:
    value: 4
pooling_mode:
    value: mean
rho:
    value: 0
shuffle:
    value: true
tau:
    value: 0.1
weight_decay:
    value: 0.01
whisper_model_id:
    value: openai/whisper-medium
